### PR TITLE
Updates to new pass manager and new passes

### PR DESCRIPTION
**Pull request by colinschmidt**
This is now up to date with this [firrtl](https://github.com/ucb-bar/firrtl/tree/5b35f2d2722f72c81d2d6c507cd379be2a1476d8) (current master), including calling the new clock list transform.

rocket-chip has not been bumped to use this version of firrtl yet.

### CODE REVIEW

**Comment by colinschmidt** [comment]
Do not merge, these updates actually broke the GenerateTop GenerateHarness splitting functionality, working on a fix now.

**Comment by colinschmidt** [comment]
Made a typo in what form to run the RemoveUnusedModules pass so the order of the passes got flipped causing the issue.

**Comment by palmer-dabbelt** [comment]
@colinschmidt I'm going to merge this, I bumped Rocket Chip last night so I'm on the latest upstream stuff.  Is there any reason I shouldn't?

**Comment by colinschmidt** [comment]
This has been replaced with ucb-bar/barstools

**Pull request closed without merging**
